version: 0.2

phases:
  install:
    commands:
      - echo "This buildspec is based on image - aws/codebuild/nodejs:8.10.0"
      - sudo apt update
      - sudo apt install python3
      - sudo apt install python3-pip
  pre_build:
    commands:
      - echo "Installing dependencies and executing unit tests - `pwd`"
      - cd deployment && chmod +x ./run-unit-tests.sh && ./run-unit-tests.sh
      - echo "Installing dependencies and executing unit tests completed `date`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - chmod +x ./build-s3-dist.sh && ./build-s3-dist.sh $DIST_OUTPUT_BUCKET $VERSION
      - echo "Build completed `date`"
      - echo "Starting open-source-dist `date` in `pwd`"
      - chmod +x ./build-open-source-dist.sh && ./build-open-source-dist.sh
      - echo "Open Source Dist completed `date`"

  post_build:
    commands:
      - echo "Copying new buildspec `date` in `pwd`"
      - mv ./buildspecs/$PIPELINE_TYPE-s3-spec.yml ../buildspec.yml
      - echo "Copying new buildspec complete `date`"
      - echo "Post build completed on `date`"

artifacts:
  files:
      - deployment/**/*
      - buildspec.yml
