Description: '(SO0013) - Live Streaming on AWS'

Parameters:

  InputType:
    Description: Specify the input type for MediaLive
    Type: String
    Default: RTP_PUSH
    AllowedValues:
      - RTP_PUSH
      - RTMP_PUSH
      - RTMP_PULL
      - URL_PULL
      - DEMO

  InputCodec:
    Description: Specify the codec of the source stream for MediaLive (AVC/HEVC/MPEG2)
    Type: String
    Default: AVC
    AllowedValues:
      - AVC
      - HEVC
      - MPEG2

  InputRes:
    Description: Specify the resolution of the source stream for MediaLive (SD/HD)
    Type: String
    Default: 1080
    AllowedValues:
      - 1080
      - 720
      - 480

  InputCIDR:
    Description: Specify the CIDR Block for the MediaLive SecurityGroup
    Type: String
    Default: "0.0.0.0/0"

  PriPullURL:
    Description: Specify the primary source URL for the PULL input stream
    Type: String

  PriPullUser:
    Description: (Optional) Specify a Username for the primary source URL
    Type: String

  PriPullPass:
    Description: (Optional) Specify a Password for the primary source URL
    Type: String

  SecPullURL:
    Description: Specify the secondary source URL for the PULL input stream
    Type: String

  SecPullUser:
    Description: (Optional) Specify a Username for the secondary source URL
    Type: String

  SecPullPass:
    Description: (Optional) Specify a Username for the secondary source URL
    Type: String

Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
            -
              Label:
                default: Live Stream Source
              Parameters:
                - InputType
                - InputCodec
                - InputRes
            -
              Label:
                default: For PUSH Source Input Types
              Parameters:
                - InputCIDR
            -
              Label:
                default: For PULL Source Input Types
              Parameters:
                - PriPullURL
                - PriPullUser
                - PriPullPass
                - SecPullURL
                - SecPullUser
                - SecPullPass
        ParameterLabels:
          InputType:
            default: Source Input Type
          InputCodec:
            default: Source Codec
          InputRes:
            default: Source Resolution
          InputCIDR:
            default: Input CIDR Block
          PriPullURL:
            default: Primary Source URL
          PriPullUser:
            default: Primary Source Username
          PriPullPass:
            default: Primary Source Password
          SecPullURL:
            default: Secondary Source URL
          SecPullUser:
            default: Secondary Source Username
          SecPullPass:
            default: Secondary Source Password

Mappings:
  SourceCode:
    General:
      S3Bucket: CODEBUCKET
      KeyPrefix: live-streaming-on-aws/CODEVERSION

  AnonymousData:
    SendAnonymousData:
      Data: Yes

Conditions:
    Metrics: !Equals [ !FindInMap [AnonymousData,SendAnonymousData,Data], Yes ]

Resources:

  CustomResourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        -
          PolicyName: !Sub "${AWS::StackName}-custom-resource"
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Join ["", ["arn:aws:logs:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":log-group:/aws/lambda/*"]]
              -
                Effect: Allow
                Action:
                  - medialive:createInputSecurityGroup
                  - medialive:createInput
                  - medialive:deleteInput
                  - medialive:createChannel
                  - medialive:deleteChannel

                Resource:
                    - !Join ["", ["arn:aws:medialive:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":*"]]
              -
                Effect: Allow
                Action:
                  - mediapackage:createChannel
                  - mediapackage:deleteChannel
                  - mediapackage:listOriginEndpoints
                  - mediapackage:deleteOriginEndpoint
                  - mediapackage:createOriginEndpoint

                Resource:
                    - !Join ["", ["arn:aws:mediapackage:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":*"]]
              -
                Effect: Allow
                Action:
                  - ssm:PutParameter
                Resource:
                  - !Join ["", ["arn:aws:ssm:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":parameter/*"]]
              -
                Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !Join ["", ["arn:aws:iam::", Ref: "AWS::AccountId", ":role/*"]]

  MediaLiveRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - "medialive.amazonaws.com"
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: !Sub "${AWS::StackName}-mediatranscode-role"
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - ssm:DescribeParameters
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:PutParameter
                Resource:
                  - !Join ["", ["arn:aws:ssm:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":parameter/*"]]

  CustomResource:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-livestream-custom-resources
      Description: Used to deploy custom resources and send AnonymousData
      Handler: index.handler
      Role: !GetAtt CustomResourceRole.Arn
      Code:
        S3Bucket: !Join ["-", [!FindInMap ["SourceCode", "General", "S3Bucket"], Ref: "AWS::Region"]]
        S3Key: !Join ["/", [!FindInMap ["SourceCode", "General", "KeyPrefix"],  "custom-resources.zip"]]
      Runtime:  nodejs6.10
      Timeout: 180

  MediaLiveInput:
    DependsOn: MediaPackageChannel
    Type: Custom::MediaLiveInput
    Properties:
      ServiceToken:  !GetAtt CustomResource.Arn
      StreamName: !Sub ${AWS::StackName}-livestream
      Type: !Ref InputType
      Cidr: !Ref InputCIDR
      PriUrl: !Ref PriPullURL
      PriUser: !Ref PriPullUser
      PriPass: !Ref PriPullPass
      SecUrl: !Ref SecPullURL
      SecUser: !Ref SecPullUser
      SecPass: !Ref SecPullPass

  MediaLiveChannel:
    DependsOn: MediaLiveInput
    Type: Custom::MediaLiveChannel
    Properties:
      ServiceToken:  !GetAtt CustomResource.Arn
      Name: !Sub ${AWS::StackName}-livestream
      Resolution: !Ref InputRes
      Codec: !Ref InputCodec
      Role: !GetAtt MediaLiveRole.Arn
      InputId: !GetAtt MediaLiveInput.Id
      MediaPackagePriUrl: !GetAtt MediaPackageChannel.Url
      MediaPackagePriUser: !GetAtt MediaPackageChannel.User
      MediaPackagePriPassParam: !GetAtt MediaPackageChannel.PassParam

  MediaPackageChannel:
    Type: Custom::MediaPackageChannel
    Properties:
      ServiceToken:  !GetAtt CustomResource.Arn
      ChannelId: !Sub ${AWS::StackName}-livestream

  MediaPackageHlsEndpoint:
    DependsOn: MediaPackageChannel
    Type: Custom::MediaPackageHlsEndpoint
    Properties:
      ServiceToken: !GetAtt CustomResource.Arn
      ChannelId: !Sub ${AWS::StackName}-livestream

  MediaPackageDashEndpoint:
    DependsOn: MediaPackageChannel
    Type: Custom::MediaPackageDashEndpoint
    Properties:
      ServiceToken: !GetAtt CustomResource.Arn
      ChannelId: !Sub ${AWS::StackName}-livestream

  MediaPackageMssEndpoint:
    DependsOn: MediaPackageChannel
    Type: Custom::MediaPackageMssEndpoint
    Properties:
      ServiceToken: !GetAtt CustomResource.Arn
      ChannelId: !Sub ${AWS::StackName}-livestream

  Uuid:
    Condition: Metrics
    Type: "Custom::UUID"
    Properties:
      ServiceToken: !GetAtt CustomResource.Arn

  AnonymousMetric:
    Condition: Metrics
    Type: "Custom::AnonymousMetric"
    Properties:
      ServiceToken: !GetAtt CustomResource.Arn
      SolutionId: "SO0013"
      UUID: !GetAtt Uuid.UUID
      Version: "2.0"
      InputType: !Ref InputType
      InputCodec: !Ref InputCodec
      InputRes: !Ref InputRes
      InputCIDR: !Ref InputCIDR
      PriPullURL: !Ref PriPullURL
      PriPullUser: !Ref PriPullUser
      PriPullPass: !Ref PriPullPass
      SecPullURL: !Ref SecPullURL
      SecPullUser: !Ref SecPullUser
      SecPullPass: !Ref SecPullPass

Outputs:
  UUID:
    Condition: Metrics
    Description: AnonymousMetric UUID
    Value: !GetAtt Uuid.UUID

  MediaLivePrimaryEndpoint:
    Description: Primary MediaLive input Url
    Value: !GetAtt MediaLiveInput.EndPoint1

  MediaLiveSecondaryEndpoint:
    Description: Primary MediaLive input Url
    Value: !GetAtt MediaLiveInput.EndPoint2

  #CloudFrontHlsEnpoint:
  #CloudFrontDashEnpoint:
  #CloudFrontMssEnpoint:
  #DemoConsoleUrl:
