Description: '(SO0013) - Live Streaming on AWS'

Parameters:

  Code:
    Description: Select the Code Base to use to deploy the media services.
    Type: String
    AllowedValues:
      - NodeJS-8.10
      - Python-3.6

  Console:
    Description: Deploy the demo console (preview player) to Amazon S3
    Type: String
    Default: Yes
    AllowedValues:
      - Yes
      - No

  InputType:
    Description: Specify the input type for MediaLive (Default parametrs are for the Demo video)
    Type: String
    Default: URL_PULL
    AllowedValues:
      - RTP_PUSH
      - RTMP_PUSH
      - RTMP_PULL
      - URL_PULL
      - MEDIACONNECT

  InputCodec:
    Description: Specify the codec of the source stream for MediaLive (AVC/HEVC/MPEG2)
    Type: String
    Default: AVC
    AllowedValues:
      - AVC
      - HEVC
      - MPEG2

  InputRes:
    Description: Specify the Encoding Profile to use for MediaLive
    Type: String
    Default: 1080
    AllowedValues:
      - 1080
      - 720
      - 540

  InputCIDR:
    Description: Specify the CIDR Block for the MediaLive SecurityGroup
    Type: String
    Default: ""

  PriPullURL:
    Description: Specify the primary source URL for the PULL input stream
    Type: String
    Default: "https://d15an60oaeed9r.cloudfront.net/live_stream_v2/sports_reel_with_markers.m3u8"

  PriPullUser:
    Description: (Optional) Specify a Username for the primary source URL
    Type: String
    Default: ""

  PriPullPass:
    Description: (Optional) Specify a Password for the primary source URL
    Type: String
    Default: ""

  SecPullURL:
    Description: Specify the secondary source URL for the PULL input stream
    Type: String
    Default: "https://d3h5srgm8b0t83.cloudfront.net/live_stream_v2/sports_reel_with_markers.m3u8"

  SecPullUser:
    Description: (Optional) Specify a Username for the secondary source URL
    Type: String
    Default: ""

  SecPullPass:
    Description: (Optional) Specify a Username for the secondary source URL
    Type: String
    Default: ""

  PriMediaConnectArn:
    Description: (Optional) Specify the Arn for MediaConnect as a source
    Type: String
    Default: ""

  SecMediaConnectArn:
    Description: (Optional) Specify the Arn for MediaConnect as a source
    Type: String
    Default: ""

Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
            -
              Label:
                default: Deployment Options
              Parameters:
                - Code
                - Console
            -
              Label:
                default: Live Stream Source
              Parameters:
                - InputType
                - InputCodec
                - InputRes
            -
              Label:
                default: For PUSH Source Types
              Parameters:
                - InputCIDR
            -
              Label:
                default: For PULL Source Types
              Parameters:
                - PriPullURL
                - PriPullUser
                - PriPullPass
                - SecPullURL
                - SecPullUser
                - SecPullPass
            -
              Label:
                default: For MediaConnect Source Type
              Parameters:
                - PriMediaConnectArn
                - SecMediaConnectArn

        ParameterLabels:
          InputType:
            default: Source Input Type
          InputCodec:
            default: Source Codec
          InputRes:
            default: Encoding Profile
          InputCIDR:
            default: Input CIDR Block
          PriPullURL:
            default: Primary Source URL
          PriPullUser:
            default: Primary Source Username
          PriPullPass:
            default: Primary Source Password
          SecPullURL:
            default: Secondary Source URL
          SecPullUser:
            default: Secondary Source Username
          SecPullPass:
            default: Secondary Source Password
          Console:
            default: Demo Console
          Code:
            default: Source Code
          PriMediaConnectArn:
            default: Primary MediaConnect Arn
          SecMediaConnectArn:
            default: Secondary MediaConnect Arn

Mappings:
  SourceCode:
    General:
      S3Bucket: CODEBUCKET
      KeyPrefix: live-streaming-on-aws/CODEVERSION

  AnonymousData:
    SendAnonymousData:
      Data: Yes

Conditions:
    Metrics: !Equals [ !FindInMap [AnonymousData,SendAnonymousData,Data], Yes]
    Demo: !Equals [ !Ref Console , Yes ]
    CodeBase: !Equals [!Ref Code, NodeJS-8.10]

Resources:

  MediaLiveRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - "medialive.amazonaws.com"
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: !Sub "${AWS::StackName}-mediatranscode-role"
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - ssm:DescribeParameters
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:PutParameter
                Resource:
                  - !Join ["", ["arn:aws:ssm:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":parameter/*"]]
              -
                Effect: Allow
                Actions:
                  - mediaconnect:ManagedDescribeFlow
                  - mediaconnect:ManagedAddOutput
                  - mediaconnect:ManagedRemoveOutput
                Resource:
                  - !Join ["", ["arn:aws:mediaconnect:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":flow/*"]]


  MediaPackageChannel:
    Type: Custom::MediaPackageChannel
    Properties:
      ServiceToken: arn:aws:lambda:us-east-1:208800812415:function:python
      Resource: MediaPackageChannel
      ChannelId: !Sub ${AWS::StackName}-livestream

  MediaPackageHlsEndpoint:
    DependsOn: MediaPackageChannel
    Type: Custom::MediaPackageHlsEndpoint
    Properties:
      ServiceToken: arn:aws:lambda:us-east-1:208800812415:function:python
      Resource: MediaPackageEndPoint
      EndPoint: HLS
      ChannelId: !GetAtt MediaPackageChannel.ChannelId

  MediaPackageDashEndpoint:
    DependsOn: MediaPackageChannel
    Type: Custom::MediaPackageDashEndpoint
    Properties:
      ServiceToken: arn:aws:lambda:us-east-1:208800812415:function:python
      Resource: MediaPackageEndPoint
      EndPoint: DASH
      ChannelId: !GetAtt MediaPackageChannel.ChannelId

  MediaPackageMssEndpoint:
    DependsOn: MediaPackageChannel
    Type: Custom::MediaPackageMssEndpoint
    Properties:
      ServiceToken: arn:aws:lambda:us-east-1:208800812415:function:python
      Resource: MediaPackageEndPoint
      EndPoint: MSS
      ChannelId: !GetAtt MediaPackageChannel.ChannelId

  MediaPackageCmafEndpoint:
    DependsOn: MediaPackageChannel
    Type: Custom::MediaPackageCmafEndpoint
    Properties:
      ServiceToken: arn:aws:lambda:us-east-1:208800812415:function:python
      Resource: MediaPackageEndPoint
      EndPoint: CMAF
      ChannelId: !GetAtt MediaPackageChannel.ChannelId

  MediaLiveInput:
    Type: Custom::MediaLiveInput
    Properties:
      ServiceToken: arn:aws:lambda:us-east-1:208800812415:function:python
      Resource: MediaLiveInput
      StreamName: !Sub ${AWS::StackName}-livestream
      Type: !Ref InputType
      Cidr: !Ref InputCIDR
      PriUrl: !Ref PriPullURL
      PriUser: !Ref PriPullUser
      PriPass: !Ref PriPullPass
      SecUrl: !Ref SecPullURL
      SecUser: !Ref SecPullUser
      SecPass: !Ref SecPullPass

  MediaLiveChannel:
    DependsOn: MediaLiveInput
    DependsOn: MediaPackageChannel
    Type: Custom::MediaLiveChannel
    Properties:
      ServiceToken: arn:aws:lambda:us-east-1:208800812415:function:python
      Resource: MediaLiveChannel
      Name: !Sub ${AWS::StackName}-livestream
      Resolution: !Ref InputRes
      Codec: !Ref InputCodec
      Role: !GetAtt MediaLiveRole.Arn
      InputId: !GetAtt MediaLiveInput.Id
      Type: !Ref InputType
      MediaPackagePriUrl: !GetAtt MediaPackageChannel.PrimaryUrl
      MediaPackagePriUser: !GetAtt MediaPackageChannel.PrimaryUser
      # FEATURE/P15424610 Dual ingest support for MediaPackage
      MediaPackageSecUrl: !GetAtt MediaPackageChannel.SecondaryUrl
      MediaPackageSecUser: !GetAtt MediaPackageChannel.SecondaryUser
