version: 0.2

phases:
  install:
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "nothing to do in pre_build"

  build:
    commands:
      - echo "Copying assets to output bucket `date` in `pwd`"
      - echo "Copying CFN Template to /$TEMPLATE_OUTPUT_BUCKET/live-streaming-on-aws/$VERSION"
      - aws s3 cp deployment/dist/live-streaming-on-aws.template s3://$TEMPLATE_OUTPUT_BUCKET/live-streaming-on-aws/$VERSION/ --acl bucket-owner-full-control
      - echo "Copying CFN Template to /latest/"
      - aws s3 cp deployment/dist/live-streaming-on-aws.template s3://$TEMPLATE_OUTPUT_BUCKET/live-streaming-on-aws/latest/ --acl bucket-owner-full-control
      - echo "Copying S3 assets to /$BUILD_OUTPUT_BUCKET/live-streaming-on-aws/$VERSION"
      - aws s3 cp deployment/dist/ s3://$BUILD_OUTPUT_BUCKET/live-streaming-on-aws/$VERSION/ --recursive --acl bucket-owner-full-control
      - echo "Copying S3 assets to /latest/"
      - aws s3 cp deployment/dist/ s3://$BUILD_OUTPUT_BUCKET/live-streaming-on-aws/latest/ --recursive --acl bucket-owner-full-control
      - echo "Copying GitHub assets to /$GITHUB_OUTPUT_BUCKET/"
      - aws s3 cp deployment/open-source s3://$GITHUB_OUTPUT_BUCKET/live-streaming-on-aws/$VERSION/open-source/ --recursive --acl bucket-owner-full-control
      - echo "Copying assets to output bucket complete `date`"

  post_build:
    commands:
      - echo "deployment of assets completed on `date`"
